/**
 * Shared demo project catalogue.
 * Used by:
 *   - GET /api/projects         (list page, merged with DB results)
 *   - GET /api/projects/[id]    (details page)
 */
export const DEMO_PROJECTS = [
  {
    id: 'demo-1',
    type: 'project' as const,
    title: 'Backend Python/Django Developer',
    description:
      'We need a backend developer to build REST API for our e-commerce platform. Experience with Django, PostgreSQL, and Docker required. Remote work possible.',
    company: 'TechHub KZ',
    category: 'Backend Dev',
    city: 'Almaty',
    budgetMin: 500,
    budgetMax: 1200,
    requiredSkills: ['Python', 'Django', 'PostgreSQL', 'REST API', 'Docker'],
    experienceLevel: 'JUNIOR',
    employmentType: 'part-time',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    type: 'project' as const,
    title: 'React Frontend Developer',
    description:
      'Looking for a React developer to build a modern dashboard for our analytics platform. TypeScript, Tailwind CSS, and REST API integration experience required.',
    company: 'StartupKZ',
    category: 'Frontend / UI',
    city: 'Astana',
    budgetMin: 400,
    budgetMax: 900,
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'REST API', 'Figma'],
    experienceLevel: 'JUNIOR',
    employmentType: 'project',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    type: 'project' as const,
    title: 'Data Analyst — SQL & Power BI',
    description:
      'We need a data analyst to build reporting dashboards in Power BI and write complex SQL queries for our CRM database. Experience with Excel and data visualization required.',
    company: 'Finance Pro',
    category: 'Data Analytics',
    city: 'Almaty',
    budgetMin: 350,
    budgetMax: 700,
    requiredSkills: ['SQL', 'Power BI', 'Excel', 'Data Analysis', 'Python'],
    experienceLevel: 'JUNIOR',
    employmentType: 'part-time',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    type: 'project' as const,
    title: 'ML Engineer — Recommendation System',
    description:
      'Build a content-based recommendation system for our e-learning platform using Python, scikit-learn, and FastAPI. Remote.',
    company: 'EduTech',
    category: 'AI / ML',
    city: 'Remote',
    budgetMin: 600,
    budgetMax: 1500,
    requiredSkills: ['Python', 'Machine Learning', 'scikit-learn', 'FastAPI', 'SQL'],
    experienceLevel: 'MIDDLE',
    employmentType: 'project',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    type: 'project' as const,
    title: 'Telegram Bot Developer',
    description:
      'Create a Telegram bot for order management: notifications, admin panel, integration with our CRM via REST API. Python + aiogram or python-telegram-bot.',
    company: 'AgriTech',
    category: 'Backend Dev',
    city: 'Astana',
    budgetMin: 200,
    budgetMax: 500,
    requiredSkills: ['Python', 'Telegram Bot API', 'REST API', 'aiogram'],
    experienceLevel: 'JUNIOR',
    employmentType: 'project',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    type: 'project' as const,
    title: 'UI/UX Designer — Mobile App',
    description:
      'Design the full UX flow and high-fidelity mockups for a fitness tracking mobile app. Figma, user research, prototyping required.',
    company: 'FitKZ',
    category: 'Product Design',
    city: 'Almaty',
    budgetMin: 300,
    budgetMax: 700,
    requiredSkills: ['Figma', 'UI/UX', 'Prototyping', 'User Research'],
    experienceLevel: 'JUNIOR',
    employmentType: 'project',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-7',
    type: 'project' as const,
    title: 'QA Engineer — Web Application Testing',
    description:
      'Manual and automated testing for our web platform. Experience with Playwright or Selenium, test plan writing, bug reporting in Jira.',
    company: 'QualityFirst',
    category: 'QA Testing',
    city: 'Remote',
    budgetMin: 300,
    budgetMax: 600,
    requiredSkills: ['QA Testing', 'Selenium', 'Playwright', 'Jira', 'Test Planning'],
    experienceLevel: 'JUNIOR',
    employmentType: 'part-time',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-8',
    type: 'project' as const,
    title: 'Node.js Backend Developer',
    description:
      'Build scalable REST API for our logistics platform. Node.js, Express, MongoDB, JWT authentication, and Docker deployment.',
    company: 'LogisticsPro',
    category: 'Backend Dev',
    city: 'Astana',
    budgetMin: 450,
    budgetMax: 1000,
    requiredSkills: ['Node.js', 'Express', 'MongoDB', 'JWT', 'Docker'],
    experienceLevel: 'JUNIOR',
    employmentType: 'part-time',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-9',
    type: 'project' as const,
    title: 'Flutter Mobile App Developer',
    description:
      'Develop cross-platform mobile application for event management. Flutter, Dart, Firebase, push notifications.',
    company: 'EventHub',
    category: 'Mobile Apps',
    city: 'Almaty',
    budgetMin: 500,
    budgetMax: 1200,
    requiredSkills: ['Flutter', 'Dart', 'Firebase', 'Mobile Development'],
    experienceLevel: 'MIDDLE',
    employmentType: 'project',
    source: 'demo',
    status: 'OPEN',
    createdAt: new Date().toISOString(),
  },
] as const;
