import { Schema, model, models } from 'mongoose';
const StudentProfileSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', unique: true },
  firstName: String,
  lastName: String,
  birthDate: String,
  phone: String,
  workplaceType: String,
  university: String,
  city: String,
  bio: String,
  headline: String,
  experience: String,
  projects: String,
  experienceEntries: [{
    jobTitle: String,
    employmentType: String,
    company: String,
    currentlyWorking: Boolean,
    startMonth: String,
    startYear: String,
    endMonth: String,
    endYear: String,
    location: String,
    workplaceType: String,
    description: String
  }],
  languages: String,
  achievements: String,
  volunteering: String,
  preferredRoles: String,
  skills: [String],
  experienceLevel: String,
  portfolioLinks: [String],
  certificates: [String],
  diplomas: [String],
  certificateDocuments: [{
    name: String,
    issuer: String,
    issueDate: String,
    expirationDate: String,
    doesNotExpire: Boolean,
    skillsCovered: [String],
    description: String,
    fileName: String,
    fileSize: Number,
    fileDataUrl: String
  }],
  diplomaDocuments: [{
    university: String,
    degree: String,
    fieldOfStudy: String,
    gpa: String,
    startYear: String,
    graduationYear: String,
    graduated: Boolean,
    expectedGraduationYear: String,
    notes: String,
    fileName: String,
    fileSize: Number,
    fileDataUrl: String
  }],
  interests: [String],
  githubUrl: String,
  linkedinUrl: String,
  resumeText: String,
  about: String,
  avatarDataUrl: String,
  avatar: String,
  availabilityStatus: String,
  savedProjects: [{ type: Schema.Types.ObjectId, ref: 'Project' }]
}, { timestamps: true });
export default models.StudentProfile || model('StudentProfile', StudentProfileSchema);
